### PR TITLE
Improve beta/index.html

### PR DESCRIPTION
**Pull request by rimopa**
Click [here](https://rimopa.github.io/beta/) (new) and click [here](https://scratchce.github.io/beta/) (current)
Sorry, this is my first "big" PR and I don't know much about html.
It will look better with more versions.

### CODE REVIEW

**Comment by CST1229** [comment]
Where is `#lastest/favicon.png`?

**Comment by rimopa** [comment]
> Where is `#lastest/favicon.png`?

I'm fixing it 😄 It worked because I didn't update the file so I thougth it's better than using 0.5.1/favicon.png

**Comment by rimopa** [comment]
ok, i'm going to do something more elaborate

**Comment by rimopa** [comment]
Note: It will look better with more versions

**Comment by rimopa** [comment]
Merge 😎

**Pull request merged**
